AWSTemplateFormatVersion: "2010-09-09"
Description: Codepipeline Project

Parameters:
  project:
    Type: String
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  artifactsBucketName:
    Type: String
  repositoryName:
    Type: String
  repositoryBranch:
    Type: String
    Default: main
  codePipelineRoleArn:
    Type: String
  gitConnectionArn:
    Type: String
  buildProjectName:
    Type: String
  deploymentBucketName:
    Type: String
Resources:
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Sub ${project}-${environment}-frontend-pipeline
      ArtifactStore:
        Location: !Ref artifactsBucketName
        Type: S3
      RestartExecutionOnUpdate: False
      RoleArn: !Ref codePipelineRoleArn
      Stages: 
        - Name: Source
          Actions: 
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref gitConnectionArn
                FullRepositoryId: !Ref repositoryName
                BranchName: !Ref repositoryBranch
                OutputArtifactFormat: "CODEBUILD_CLONE_REF"
                DetectChanges: false
              RunOrder: 1
              OutputArtifacts:
                - Name: Source
              Namespace: SourceVariables
        - Name: Build
          Actions: 
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref buildProjectName
              RunOrder: 1
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: Build
              Namespace: BuildVariables
        - Name: Deploy
          Actions: 
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !Ref deploymentBucketName
                Extract: 'true'
                # ObjectKey: v1
              RunOrder: 1
              InputArtifacts:
                - Name: Build
              Namespace: DeployVariables
Outputs:
  codePipelineProjectName:
    Value: !Ref CodePipelineProject
  codePipelineProjectArn:
    Value: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipelineProject}