AWSTemplateFormatVersion: "2010-09-09"
Description: Codebuild Project

Parameters:
  project:
    Type: String
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  subdomain:
    Type: String
  buildSpecPath:
    Type: String
    Default: buildspec.yml
  computeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
      - BUILD_GENERAL1_2XLARGE
  codeBuildRoleArn:
    Type: String
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Sub ${project}-${environment}-website-${subdomain}-build
      Description: Build project
      Artifacts: 
        Type: CODEPIPELINE
      BadgeEnabled: False
      Environment: 
        ComputeType: !Ref computeType
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: True
        Type: LINUX_CONTAINER
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Ref codeBuildRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref buildSpecPath
      TimeoutInMinutes: 60
      Visibility: PRIVATE

Outputs:
  codeBuildProjectName:
    Value: !Ref CodeBuildProject
  codeBuildProjectArn:
    Value: !GetAtt CodeBuildProject.Arn