Parameters:
  project:
    Type: String
    Description: Project's name
    MinLength: "4"
    MaxLength: "12"
    AllowedPattern: ^(\d|\w)+$
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  subdomain:
    Type: String
  buildSpecPath:
    Type: String
    Default: buildspec.yml
  cfnBucketName:
    Type: String
    Description: Bucket that store cfn modules
  frontendRepository:
    Type: String
  repositoryBranch:
    Type: String
    Default: main
  artifactsBucketName:
    Type: String
  deploymentBucket:
    Type: String
  gitConnectionArn:
    Type: String
  automaticDeploy:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  buildInstanceComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
      - BUILD_GENERAL1_2XLARGE
Resources:
  Permissions:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/iam.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        subdomain: !Ref subdomain
        artifactsBucketName: !Ref artifactsBucketName
        deploymentBucketName: !Ref deploymentBucket

  BuildProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/codebuild.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        subdomain: !Ref subdomain
        buildSpecPath: !Ref buildSpecPath
        computeType: !Ref buildInstanceComputeType
        codeBuildRoleArn: !GetAtt Permissions.Outputs.buildRoleArn
        
  PipelineProject:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub https://s3.amazonaws.com/${cfnBucketName}/${project}/frontend/modules/pipeline/codepipeline.yml
      Parameters: 
        project: !Ref project
        environment: !Ref environment
        subdomain: !Ref subdomain
        artifactsBucketName: !Ref artifactsBucketName
        repositoryName: !Ref frontendRepository
        repositoryBranch: !Ref repositoryBranch
        codePipelineRoleArn: !GetAtt Permissions.Outputs.pipelineRoleArn
        gitConnectionArn: !Ref gitConnectionArn
        buildProjectName: !GetAtt BuildProject.Outputs.codeBuildProjectName
        deploymentBucket: !Ref deploymentBucket
        automaticDeploy: !Ref automaticDeploy